/**
 * Stats Options and related data structures
 * Migrated from t4stat.js OPTIONS array to React module
 */

import { STAT_CATEGORIES, MATERIAL_TYPES, BONUS_STEPS } from './constants';

export const OPTIONS = [
  {
    name: "STR",
    mat: MATERIAL_TYPES.BEAST,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_STATS,
    type: "u",
    bonus: 1,
  },
  {
    name: "STR %",
    mat: MATERIAL_TYPES.BEAST,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_STATS,
    type: "u",
  },
  {
    name: "INT",
    mat: MATERIAL_TYPES.WOOD,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_STATS,
    type: "u",
    bonus: 1,
  },
  {
    name: "INT %",
    mat: MATERIAL_TYPES.WOOD,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_STATS,
    type: "u",
  },
  {
    name: "VIT",
    mat: MATERIAL_TYPES.METAL,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_STATS,
    type: "u",
    bonus: 1,
  },
  {
    name: "VIT %",
    mat: MATERIAL_TYPES.METAL,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_STATS,
    type: "u",
  },
  {
    name: "AGI",
    mat: MATERIAL_TYPES.CLOTH,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_STATS,
    type: "u",
    bonus: 1,
  },
  {
    name: "AGI %",
    mat: MATERIAL_TYPES.CLOTH,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_STATS,
    type: "u",
  },
  {
    name: "DEX",
    mat: MATERIAL_TYPES.MEDICINE,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_STATS,
    type: "u",
    bonus: 1,
  },
  {
    name: "DEX %",
    mat: MATERIAL_TYPES.MEDICINE,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_STATS,
    type: "u",
  },

  {
    name: "Natural HP Regen",
    mat: MATERIAL_TYPES.METAL,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_HP_MP,
    type: "a",
    bonus: 1,
  },
  {
    name: "Natural HP Regen %",
    mat: MATERIAL_TYPES.METAL,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_HP_MP,
    type: "a",
  },
  {
    name: "Natural MP Regen",
    mat: MATERIAL_TYPES.WOOD,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_HP_MP,
    type: "a",
    bonus: 1,
    bonusratio: 0.5,
  },
  {
    name: "Natural MP Regen %",
    mat: MATERIAL_TYPES.WOOD,
    pot: 20,
    cost: 100,
    cat: STAT_CATEGORIES.ENHANCE_HP_MP,
    type: "a",
  },
  {
    name: "MaxHP",
    mat: MATERIAL_TYPES.METAL,
    pot: 3,
    cost: "16.49",
    cat: STAT_CATEGORIES.ENHANCE_HP_MP,
    type: "u",
    bonus: 160,
    step: 10,
  },
  {
    name: "MaxHP %",
    mat: MATERIAL_TYPES.METAL,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_HP_MP,
    type: "u",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "MaxMP",
    mat: MATERIAL_TYPES.WOOD,
    pot: 6,
    cost: "33.49",
    cat: STAT_CATEGORIES.ENHANCE_HP_MP,
    type: "u",
    max: 15,
    max_only: true,
    step: 10,
    bonus: 10,
    bonusratio: 0.5,
  },

  {
    name: "ATK",
    mat: MATERIAL_TYPES.BEAST,
    pot: 3,
    cost: "16.49",
    cat: STAT_CATEGORIES.ENHANCE_ATTACK,
    type: "w",
    bonus: 1,
  },
  {
    name: "ATK %",
    mat: MATERIAL_TYPES.BEAST,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_ATTACK,
    type: "w",
    bonus: 1,
    bonusratio: 0.5,
  },
  {
    name: "MATK",
    mat: MATERIAL_TYPES.WOOD,
    pot: 3,
    cost: "16.49",
    cat: STAT_CATEGORIES.ENHANCE_ATTACK,
    type: "w",
    bonus: 1,
  },
  {
    name: "MATK %",
    mat: MATERIAL_TYPES.WOOD,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_ATTACK,
    type: "w",
    bonus: 1,
    bonusratio: 0.5,
  },
  {
    name: "Stability %",
    mat: MATERIAL_TYPES.MEDICINE,
    pot: 20,
    cost: 100,
    cat: STAT_CATEGORIES.ENHANCE_ATTACK,
    type: "u",
  },
  {
    name: "Physical Pierce %",
    mat: MATERIAL_TYPES.BEAST,
    pot: 20,
    cost: 100,
    cat: STAT_CATEGORIES.ENHANCE_ATTACK,
    type: "w",
    bonus: 1,
    bonusratio: 2 / 5,
  },
  {
    name: "Magic Pierce %",
    mat: MATERIAL_TYPES.WOOD,
    pot: 20,
    cost: 100,
    cat: STAT_CATEGORIES.ENHANCE_ATTACK,
    type: "w",
    bonus: 1,
    bonusratio: 2 / 5,
  },

  {
    name: "DEF",
    mat: MATERIAL_TYPES.METAL,
    pot: 3,
    cost: "16.49",
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    bonus: 10,
  },
  {
    name: "DEF %",
    mat: MATERIAL_TYPES.METAL,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "MDEF",
    mat: MATERIAL_TYPES.METAL,
    pot: 3,
    cost: "16.49",
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    bonus: 10,
  },
  {
    name: "MDEF %",
    mat: MATERIAL_TYPES.METAL,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "Physical Resistance %",
    mat: MATERIAL_TYPES.METAL,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "Magical Resistance %",
    mat: MATERIAL_TYPES.WOOD,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    bonus: 1,
    bonusratio: 1 / 3,
  },

  {
    name: "Reduce Dmg (Foe Epicenter) %",
    mat: MATERIAL_TYPES.METAL,
    pot: 6,
    cost: 15,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Player Epicenter) %",
    mat: MATERIAL_TYPES.METAL,
    pot: 6,
    cost: 15,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Straight Line) %",
    mat: MATERIAL_TYPES.WOOD,
    pot: 6,
    cost: 15,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Charge) %",
    mat: MATERIAL_TYPES.WOOD,
    pot: 6,
    cost: 15,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Meteor) %",
    mat: MATERIAL_TYPES.WOOD,
    pot: 4,
    cost: 15,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Bullet) %",
    mat: MATERIAL_TYPES.WOOD,
    pot: 4,
    cost: 15,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Bowling) %",
    mat: MATERIAL_TYPES.WOOD,
    pot: 4,
    cost: 15,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Floor) %",
    mat: MATERIAL_TYPES.WOOD,
    pot: 4,
    cost: 15,
    cat: STAT_CATEGORIES.ENHANCE_DEFENSE,
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },

  {
    name: "Accuracy",
    mat: MATERIAL_TYPES.MEDICINE,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_ACCURACY,
    type: "w",
    bonus: 2,
    bonusratio: 2 / 3,
  },
  {
    name: "Accuracy %",
    mat: MATERIAL_TYPES.MEDICINE,
    pot: 20,
    cost: 100,
    cat: STAT_CATEGORIES.ENHANCE_ACCURACY,
    type: "w",
    bonus: 1,
    bonusratio: 1 / 5,
  },

  {
    name: "Dodge",
    mat: MATERIAL_TYPES.CLOTH,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_DODGE,
    type: "a",
    bonus: 2,
    bonusratio: 2 / 3,
  },
  {
    name: "Dodge %",
    mat: MATERIAL_TYPES.CLOTH,
    pot: 20,
    cost: 100,
    cat: STAT_CATEGORIES.ENHANCE_DODGE,
    type: "a",
  },

  {
    name: "ASPD",
    mat: MATERIAL_TYPES.CLOTH,
    pot: 1,
    cost: "1.49",
    cat: STAT_CATEGORIES.ENHANCE_SPEED,
    type: "u",
    bonus: 16,
  },
  {
    name: "ASPD %",
    mat: MATERIAL_TYPES.CLOTH,
    pot: 1,
    cost: 5,
    cat: STAT_CATEGORIES.ENHANCE_SPEED,
    type: "u",
  },
  {
    name: "CSPD",
    mat: MATERIAL_TYPES.MEDICINE,
    pot: 1,
    cost: "1.49",
    cat: STAT_CATEGORIES.ENHANCE_SPEED,
    type: "u",
    bonus: 16,
  },
  {
    name: "CSPD %",
    mat: MATERIAL_TYPES.MEDICINE,
    pot: 1,
    cost: 5,
    cat: STAT_CATEGORIES.ENHANCE_SPEED,
    type: "u",
  },

  {
    name: "Critical Rate",
    mat: MATERIAL_TYPES.MANA,
    pot: 1,
    cost: 5,
    cat: STAT_CATEGORIES.ENHANCE_CRITICAL,
    type: "u",
    bonus: 1,
    max_only: true,
  },
  {
    name: "Critical Rate %",
    mat: MATERIAL_TYPES.MANA,
    pot: 1,
    cost: 5,
    cat: STAT_CATEGORIES.ENHANCE_CRITICAL,
    type: "u",
    bonus: 1,
    max_only: true,
  },
  {
    name: "Critical Damage",
    mat: MATERIAL_TYPES.MANA,
    pot: 3,
    cost: "16.49",
    cat: STAT_CATEGORIES.ENHANCE_CRITICAL,
    type: "u",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "Critical Damage %",
    mat: MATERIAL_TYPES.MANA,
    pot: 10,
    cost: 50,
    cat: STAT_CATEGORIES.ENHANCE_CRITICAL,
    type: "u",
    bonus: 1,
    bonusratio: 1 / 8,
  },

  {
    name: "% stronger against Fire",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "% stronger against Water",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "% stronger against Wind",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "% stronger against Earth",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "% stronger against Light",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "% stronger against Dark",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "Fire resistance %",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },
  {
    name: "Water resistance %",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },
  {
    name: "Wind resistance %",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },
  {
    name: "Earth resistance %",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },
  {
    name: "Light resistance %",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },
  {
    name: "Dark resistance %",
    mat: MATERIAL_TYPES.MANA,
    pot: 5,
    cost: 25,
    cat: STAT_CATEGORIES.ENHANCE_ELEMENTS,
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },

  {
    name: "Ailment Resistance %",
    mat: MATERIAL_TYPES.MANA,
    pot: 20,
    cost: 100,
    cat: STAT_CATEGORIES.SPECIAL_ENHANCEMENT,
    type: "u",
  },
  {
    name: "Guard Power %",
    mat: MATERIAL_TYPES.MANA,
    pot: 20,
    cost: 100,
    cat: STAT_CATEGORIES.SPECIAL_ENHANCEMENT,
    type: "u",
  },
  {
    name: "Guard Rate %",
    mat: MATERIAL_TYPES.MANA,
    pot: 20,
    cost: 100,
    cat: STAT_CATEGORIES.SPECIAL_ENHANCEMENT,
    type: "u",
  },
  {
    name: "Evasion Rate %",
    mat: MATERIAL_TYPES.MANA,
    pot: 20,
    cost: 100,
    cat: STAT_CATEGORIES.SPECIAL_ENHANCEMENT,
    type: "u",
  },
  {
    name: "Aggro %",
    mat: MATERIAL_TYPES.MANA,
    pot: 6,
    cost: "33.49",
    cat: STAT_CATEGORIES.SPECIAL_ENHANCEMENT,
    type: "u",
    max: 15,
    max_only: true,
    bonus: 1,
    bonusratio: 2 / 5,
  },

  {
    name: "Fire Element",
    mat: MATERIAL_TYPES.MANA,
    pot: 100,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Water Element",
    mat: MATERIAL_TYPES.MANA,
    pot: 100,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Wind Element",
    mat: MATERIAL_TYPES.MANA,
    pot: 100,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Earth Element",
    mat: MATERIAL_TYPES.MANA,
    pot: 100,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Light Element",
    mat: MATERIAL_TYPES.MANA,
    pot: 100,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Dark Element",
    mat: MATERIAL_TYPES.MANA,
    pot: 100,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Fire Element (matching)",
    mat: MATERIAL_TYPES.MANA,
    pot: 10,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Water Element (matching)",
    mat: MATERIAL_TYPES.MANA,
    pot: 10,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Wind Element (matching)",
    mat: MATERIAL_TYPES.MANA,
    pot: 10,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Earth Element (matching)",
    mat: MATERIAL_TYPES.MANA,
    pot: 10,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Light Element (matching)",
    mat: MATERIAL_TYPES.MANA,
    pot: 10,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Dark Element (matching)",
    mat: MATERIAL_TYPES.MANA,
    pot: 10,
    cost: 150,
    cat: STAT_CATEGORIES.AWAKEN_ELEMENTS,
    type: "e",
    max: 1,
    nonega: true,
  },
];

export default OPTIONS;